manifest:
  version: 0.13

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.7.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - hal_stm32
        path-prefix: deps

  self:
    path: app
